name: daakia_vc_flutter_sdk
description: "Flutter SDK for video conference."
version: 2.1.3
homepage: https://www.daakia.co.in/

environment:
  sdk: ^3.5.3
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  retrofit: ^4.4.2
  logger: ^2.5.0
  json_annotation: ^4.9.0
  dio: ^5.7.0
  loading_btn: ^1.0.3
  livekit_client: ^2.3.5
  fluttertoast: ^8.2.8
  pretty_dio_logger: ^1.4.0

  permission_handler: ^11.3.1
  flutter_background: ^1.3.0+1
  provider: ^6.1.2
  uuid: ^4.5.1
  intl: ^0.19.0
  collection: ^1.18.0
  flutter_webrtc: ^0.12.5+hotfix.2
  animated_emoji: ^3.1.0
  safe_device: ^1.2.0
  wakelock_plus: ^1.2.10
  package_info_plus: ^8.1.1
  simple_pip_mode: ^1.0.0
  flutter_link_previewer: ^3.2.2
  mime: ^2.0.0
  open_file: ^3.5.10
  webview_flutter: ^4.10.0
  path_provider: ^2.1.5
  file_picker: ^8.1.7
  flutter_svg: ^2.0.17
  shared_preferences: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  retrofit_generator: ^9.1.7
  build_runner: ^2.4.14
  json_serializable: ^6.9.3

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  assets:
    - assets/icons/
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/to/asset-from-package
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/to/font-from-package
