name: daakia_vc_flutter_sdk
description: "A ready-to-use Flutter SDK for seamless audio/video calls, group meetings, and scalable conferencing solutions."
version: 4.2.0
homepage: https://github.com/daakia/daakia_vc_flutter_sdk

environment:
  sdk: ^3.5.3
  flutter: ">=1.17.0"

platforms:
  android:
  ios:

dependencies:
  flutter:
    sdk: flutter

  retrofit: ^4.7.2
  logger: ^2.6.1
  json_annotation: ^4.9.0
  dio: ^5.9.0
  loading_btn: ^1.0.3
  livekit_client: ^2.5.0+hotfix.3
  fluttertoast: ^8.2.8
  pretty_dio_logger: ^1.4.0

  permission_handler: ^12.0.1
  flutter_background: ^1.3.0+1
  provider: ^6.1.5+1
  uuid: ^4.5.1
  intl: ^0.20.2
  collection: ^1.18.0
  flutter_webrtc: ^1.1.0
  animated_emoji: ^3.2.1
  safe_device: ^1.3.5
  wakelock_plus: ^1.3.2
  package_info_plus: ^8.3.1
  simple_pip_mode: ^1.0.0
  flutter_link_previewer: ^3.2.2
  flutter_chat_types: ^3.6.2
  mime: ^2.0.0
  open_file: ^3.5.10
  webview_flutter: ^4.13.0
  path_provider: ^2.1.5
  file_picker: ^10.3.2
  flutter_svg: ^2.2.0
  shared_preferences: ^2.4.0
  webview_flutter_android: ^4.10.1
  webview_flutter_wkwebview: ^3.23.0
  audioplayers: ^6.5.1
  datadog_flutter_plugin: ^2.13.1
  connectivity_plus: ^6.1.5
  device_info_plus: ^11.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  retrofit_generator: ^10.0.4
  build_runner: ^2.7.1
  json_serializable: ^6.11.0


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  assets:
    - assets/icons/
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/to/asset-from-package
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/to/font-from-package
